### ISSUE TITLE
Documentation of --version

### ISSUE THREAD

**Issue by coyotte508** [huggingface/doc-builder#105]
The current help text reads:

```
help="Version under which to push the files. Will not affect the actual files generated, as these are"
        " generated according to the `path_to_docs` argument.",
```

But now it will affect the files generated, in `kit/svelte.config.js`:

```
paths: {
			base:
				"/docs/" +
				(process.env.DOCS_LIBRARY || "transformers") +
				"/" +
				(process.env.DOCS_VERSION || "master") +
				"/" +
				(process.env.DOCS_LANGUAGE || "en")
		}
```

(it's used in the html files to reference the generated js files with an absolute path)

Maybe something like `DOCS_PATH` (= `path_to_docs`) should be passed instead? 

But the CI in transformers doesn't set `path_to_docs` :thinking: 

Edit: For the course we may want to reuse the `kit` folder of `doc-builder` with a fully configurable `paths.base` as well

**Comment by sgugger** [comment]
I don't understand what needs to be fixed here. The docstring? Or something else?

**Comment by coyotte508** [comment]
> I don't understand what needs to be fixed here. The docstring? Or something else?

- The help text for `--version`
- If `path_to_docs` is explicitly set, use that in `kit/svelte.config.js` instead of the combination of version / language / library name for `paths.base`?

I'm not clear on the role of `path_to_docs`, or if it's set to a default value even when not specified, so I may be off.

**Comment by sgugger** [comment]
It's nothing that can be set, probably some legacy argument to the build command.
