### ISSUE TITLE
[🐞BUG?] 404 errors when following Google Search Results

### ISSUE THREAD

**Issue by cakiki** [huggingface/doc-builder#125]
Hello! 

I've been getting a lot of 404's when going from google search results to doc pages on huggingface.co

Has there been a new change to how URLs are named? Because most links I follow lead to dead pages. 

e.g. googling _"dataset from pandas huggingface"_  has the following listed as first result (as well as other results that also lead to 404s): https://huggingface.co/docs/datasets/loading_datasets

cc @osanseviero

**Comment by osanseviero** [comment]
cc @mishig25 @lhoestq

**Comment by mishig25** [comment]
@cakiki thanks a lot for notifying the issue!

should be solved now 😊

please let me know if you still encounter the issue
