### ISSUE TITLE
Library package not installed while building docs

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/doc-builder#160]
We are having issues with documentation building:
- https://github.com/huggingface/datasets/runs/5716300989?check_suite_focus=true

```
ValueError: There was an error when converting ../datasets/docs/source/package_reference/main_classes.mdx to the MDX format.
Unable to find datasets.filesystems.S3FileSystem in datasets. Make sure the path to that object is correct.
```

After some investigation: 
- the issues started just after this PR was merged:
  - #154 
- looking at the corresponding action summary, it seems that the `datasets[dev]` package installation was skipped

CC: @lewtun

**Comment by lewtun** [comment]
Oh indeed, I see a weird parse error:

```
/__w/_temp/75bf1d4b-4452-4c1d-8927-838e5094620a.sh: 7: [[: not found
```

I'll revert my PR and investigate how to fix this

**Comment by albertvillanova** [comment]
@lewtun please note that I'm just guessing... Maybe your PR is not the source of the issue...

**Comment by lewtun** [comment]
I think you're guess is right @albertvillanova - from this [SO answer](https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found) it seems that the lack of bash builtins is causing the problem. I've reverted the commit in #161 so we can now see if that resolves the issue

**Comment by albertvillanova** [comment]
@lewtun I confirm that the docs building works as expected after your reversion:
- https://github.com/huggingface/datasets/runs/5718022417?check_suite_focus=true
