### ISSUE TITLE
API Doc uses gigaoctet instead of gigabyte

### ISSUE THREAD

**Issue by cakiki** [huggingface/doc-builder#196]
Wasn't sure where to open this because https://github.com/huggingface/api-inference is private.

The API Inference doc uses `Go` instead of `GB` https://huggingface.co/docs/api-inference/quicktour#using-large-models-10-go

**Comment by mishig25** [comment]
@cakiki thanks a lot for notifying! fixed it 😃
https://huggingface.co/docs/api-inference/quicktour#using-large-models-10-gb
