### ISSUE TITLE
Style replaces ... with >>>

### ISSUE THREAD

**Issue by stevhliu** [huggingface/doc-builder#206]
Not a big deal since it doesn't affect the user copying the code, but `make style` replaces `...` with `>>> ` as shown below on the lines with `commit`:

<img width="757" alt="Screen Shot 2022-04-29 at 9 49 02 AM" src="https://user-images.githubusercontent.com/59462357/165988515-b9b429a0-86f7-4fb6-85e7-0b25b16cf224.png">

cc @sgugger

**Comment by sgugger** [comment]
Note that while the bug in `doc-builder` is fixed, it looks like `huggingface_hub` is not using it anymore for styling, so this won't solve your problem there.
