### ISSUE TITLE
Backticks italicizes values inconsistently

### ISSUE THREAD

**Issue by stevhliu** [huggingface/doc-builder#208]
In the Datasets API docs, surrounding text with backticks will sometimes italicize the text instead of formatting it as code (for example, in the code example [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_4300/en/package_reference/loading_methods#datasets.load_dataset.example-3):

![Screen Shot 2022-05-12 at 11 32 02 AM](https://user-images.githubusercontent.com/59462357/168144552-961f7a6d-f219-4c5b-b1bc-94751386b8a9.png)

But if we look at [GeneratorBasedBuilder](https://huggingface.co/docs/datasets/package_reference/builder_classes#datasets.GeneratorBasedBuilder), the backticks will correctly format the text as code.

**Comment by albertvillanova** [comment]
@stevhliu the link to `IterableDataset` is not properly formatted either:
```
Load an [IterableDataset]:
```
Do you know why?

**Comment by stevhliu** [comment]
I'm not entirely sure! 😅 Maybe @mishig25 can help? Some more interesting quirks I found: 

- Using double backticks [here](https://github.com/huggingface/datasets/blob/2f9a6a5bf3e25944b3620c870896dce0c8c0d52f/src/datasets/load.py#L1610) correctly formats the text as code. 
- Using the rST format for `IterableDataset` appears to work [here](https://github.com/huggingface/datasets/blob/2f9a6a5bf3e25944b3620c870896dce0c8c0d52f/src/datasets/load.py#L1706) as well. 

I think eventually I'll clean up all the leftover rST goodness and convert them to use the new syntax so it is easier to read.

**Comment by mishig25** [comment]
Will definitely investigate this issue, thanks a lot for supplying concrete examples as they are super helpful in debugging

**Comment by stevhliu** [comment]
Closing because this issue is solved. `doc-builder` doesn't like it when Markdown and rST syntax is mixed together in a docstring :)
