### ISSUE TITLE
How to render class args?

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/doc-builder#234]
I am trying to make appear in the docs the class args for `datasets.DatasetBuilder` without success: 
- huggingface/datasets/pull/4429

I have tried:
- putting args in docstring at the class level and also at the `__init__` method
- adding "all" to autodoc directive

I took as example `transformers.Trainer`: https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer

What should I do to make it work?
Thank you.

P.S.: I open an issue as I think this might be useful to other users as well.

**Comment by albertvillanova** [comment]
There was a parsing error due to missing arg type. This commit makes the arg appear: https://github.com/huggingface/datasets/pull/4429/commits/da5edf6bc27dc02bed0f4e580e609fe3bf3cb5e2

Maybe we should support args without type and render them as well?

**Comment by mishig25** [comment]
I can work on it but we want to have types in their args all the time, no?
cc: @sgugger

**Comment by sgugger** [comment]
Yes I don't think we want to support args with no types (note that just an empty pair of parenthesis would work by the way). This was a syntax error IMO.

**Comment by albertvillanova** [comment]
What about if we would like to document `*args` and/or `**kwargs`? Normally, these have no types...

See:
- #235

**Comment by sgugger** [comment]
In the example you point out, a parenthesis is missing at the end of "(Optional ``datasets.DownloadConfig``"
```
download_config (Optional ``datasets.DownloadConfig``: specific download configuration parameters.
```
which doesn't help.

As for kwargs, we always add something in Transformers like this:
```
**kwargs (additional keyword arguments):
```
or
```
kwargs (remaining dictionary of keyword arguments, *optional*):
```
or 
```
kwargs (`Dict[str, Any]`, *optional*):
```
