### ISSUE TITLE
Linking to a URL inside a tip doesn't render properly

### ISSUE THREAD

**Issue by muellerzr** [huggingface/doc-builder#267]
See an example here:
https://moon-ci-docs.huggingface.co/docs/accelerate/pr_495/en/usage_guides/notebook#launching-multinode-training-from-a-jupyter-environment

I'd expect to be able to do:

```markdown
<Tip>
  [Here](https://myurl.com)
</Tip>
```
just fine, but instead the URL is not generated

**Comment by mishig25** [comment]
[The markdown parser](https://github.com/pngwn/MDsveX) expects newlines inside `<Tip>` for the content to be rendered as markdown:
```md
<Tip>

  [Here](https://myurl.com)

</Tip>
```

Please let me know if it solves your problem 😊
