### ISSUE TITLE
Add ability to build from repos under different org/user

### ISSUE THREAD

**Issue by nateraw** [huggingface/doc-builder#300]
Right now I'm trying to set up hugging face docs for `timm`, which is under `rwightman`'s username. Would it make sense to add an input in `build_main_documentation.yml` to optionally override the repo owner of the repo you're trying to build documentation for?

Looks like we could do that, then just replace `huggingface` [here](https://github.com/huggingface/doc-builder/blob/da021d60070ff3bc5a33be7fc457656d242ba6cb/.github/workflows/build_main_documentation.yml#L49) with a new input, `${{ inputs.repository_owner }}`, that defaults to `huggingface`.

**Comment by julien-c** [comment]
sounds like a good request

**Comment by nateraw** [comment]
Ok, I'll give this a go then and see what happens :)

**Comment by nateraw** [comment]
PR is in! feel free to take a look
