### ISSUE TITLE
Build docs using package name that differs from repo name

### ISSUE THREAD

**Issue by nateraw** [huggingface/doc-builder#305]
I am currently working on building the timm docs, which are at `rwightman/pytorch-image-models`. The package name itself is `timm`. 

As far as I understand, we use the `package` input to specify the repo name. It's used to clone the repo here:

https://github.com/huggingface/doc-builder/blob/4ac0cc8454bb5e5c875e1e11abf86b68473ca7b4/.github/workflows/build_pr_documentation.yml#L56

Apparently `package` is again used to build the documentation here:

https://github.com/huggingface/doc-builder/blob/4ac0cc8454bb5e5c875e1e11abf86b68473ca7b4/.github/workflows/build_pr_documentation.yml#L143

Why aren't we using the `package_name` env variable that was updated to be `package` if it wasn't provided to do the above `doc-builder build` command? I think this is what's going wrong with my PR [here](https://github.com/rwightman/pytorch-image-models/actions/runs/3176196617/jobs/5175209231). It leads to `ModuleNotFoundError: No module named 'pytorch-image-models'`.

Am I missing something/doing something wrong?

CC @mishig25 @osanseviero

**Comment by mishig25** [comment]
Hi Nate,

Does this example help?
In this [example](https://github.com/huggingface/hub-docs/blob/main/.github/workflows/build_documentation.yml#L15-L16), the repo name is `hub-docs`, but we want the docs to appear under `hub` (as in hf.co/docs/hub)

**Comment by nateraw** [comment]
This will still run `doc-builder build pytorch-image-models ...` though, which will fail, no? The only reason the `hub-docs` one works is because [we supplied](https://github.com/huggingface/hub-docs/blob/d63e4cd39def89fcea33abfc136f2a3a5b4299d0/.github/workflows/build_documentation.yml#L18) `--not_python_module` flag.

**Comment by nateraw** [comment]
I don't mind doing it - I'm right in my assumption that this should be the environment variable mentioned above, eh @mishig25 ?

**Comment by mishig25** [comment]
Yes 👍
