### ISSUE TITLE
Support question 😅: how to embed a HTML5 video tag

### ISSUE THREAD

**Issue by julien-c** [huggingface/doc-builder#335]
arf, this doesn't seem to work: 
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/326577/207643207-ece5b097-38d5-4f4f-a2ff-018e72248e4f.png">

@mishig25 when you're back let me know if you think of a way to enable this

_Originally posted by @julien-c in https://github.com/huggingface/hub-docs/pull/562#discussion_r1048646276_

**Comment by mishig25** [comment]
video tags are now supported in doc-builder https://github.com/huggingface/doc-builder/pull/339
