### ISSUE TITLE
How to use doc-builder to create docs-page for my own library

### ISSUE THREAD

**Issue by imflash217** [huggingface/doc-builder#338]
Hi,
Thanks for this tool. I want to use it to create docs-page for **my own library**. I could not find any information for such on the homepage/README. Can you please guide me to process for this?
Thanks

**Comment by julien-c** [comment]
this repo is not really meant for libraries outside HF, though you might have some success using it

It is mostly glue code between markdown and https://svelte.dev/, which we are using on the frontend side

Hope this helps

**Comment by imflash217** [comment]
That's very helpful @julien-c . Thanks
