### ISSUE TITLE
Support Flax notebooks

### ISSUE THREAD

**Issue by stevhliu** [huggingface/doc-builder#358]
Hi, it looks like the doc-builder only supports building Colab notebooks in PyTorch/TensorFlow at the moment. Would it be possible to extend this for Flax as well? For context, we're trying to build some notebooks for Diffusers, which uses Flax in some of the training doc examples.

cc @yiyixuxu @sgugger 

https://github.com/huggingface/doc-builder/blob/10fd3bbeb0eea8cff685e67c7ee414a211bde8fc/src/doc_builder/convert_to_notebook.py#L89

**Comment by sgugger** [comment]
That's not something I have the bandwidth to work on.
