### ISSUE TITLE
Code blocks not rendering correctly

### ISSUE THREAD

**Issue by xenova** [huggingface/doc-builder#371]
Some code blocks do not render correctly. Here's a minimal reproduction:

[index.md](https://github.com/huggingface/doc-builder/files/11360313/index2.md)
(included as a file due to code blocks)

It renders like this:
![image](https://user-images.githubusercontent.com/26504141/235329269-cc34fef7-7473-41b9-826f-558e894cc396.png)

As you can see, the first block isn't rendered correctly, while the second one is.

**Comment by xenova** [comment]
Tested on both v0.4.0 and latest git commit, both produce the same issue.

**Comment by coyotte508** [comment]
This is because you need to add a newline between the heading and the rest I think

Eg:

```
## Installation
To install via [NPM](https://www.npmjs.com/package/@xenova/transformers), run:
```

to

```
## Installation

To install via [NPM](https://www.npmjs.com/package/@xenova/transformers), run:
```

**Comment by xenova** [comment]
Oh that's strange 👀 Github markdown and my md previewer vscode extension seem to accept both. Will close, thanks!
