### ISSUE TITLE
Underscore being parsed as italic text

### ISSUE THREAD

**Issue by mishig25** [huggingface/doc-builder#40]
<img width="998" alt="Screenshot 2021-12-06 at 11 05 28" src="https://user-images.githubusercontent.com/11827707/144827285-48238634-5ba3-4ed3-a286-78119703ce5e.png">

**Comment by sgugger** [comment]
I'm changing the _ to * in #61 for italics content. It may solve this issue auto-magically.

**Comment by mishig25** [comment]
Sounds good to me !

**Comment by mishig25** [comment]
@sgugger can I close this issue?

**Comment by sgugger** [comment]
If the problem disappeared, by all means!
