### ISSUE TITLE
Remove ">>>" marker when copying code examples to clipboard

### ISSUE THREAD

**Issue by amitness** [huggingface/doc-builder#41]
Currently, the code examples on the documentation show a clipboard icon on hovering.
<img width="986" alt="Screen Shot 2021-12-06 at 9 09 00 PM" src="https://user-images.githubusercontent.com/8587189/144915052-89112ddb-0df6-406d-b62f-e98927afd06c.png">

When using that, the copied code includes the ">>>" marker before each line of code. Example
```
>>> from transformers import pipeline

>>> classifier = pipeline("sentiment-analysis")

>>> result = classifier("I hate you")[0]
>>> print(f"label: {result['label']}, with score: {round(result['score'], 4)}")
label: NEGATIVE, with score: 0.9991

>>> result = classifier("I love you")[0]
>>> print(f"label: {result['label']}, with score: {round(result['score'], 4)}")
label: POSITIVE, with score: 0.9999
```

It would be a really good user experience if the `>>>` markers are automatically removed during copying. It's a pain to manually remove them when trying some small piece of code in an interpreter or notebook.

Alternatively, you can also add a toggle to show/hide `>>>` markers similar to how [realpython.com](https://realpython.com/python-pretty-print/) does it.  

![image](https://user-images.githubusercontent.com/8587189/144915931-e88aa728-82ee-496c-a4c4-34d7c9df425d.png)

**Comment by osanseviero** [comment]
cc @mishig25 @Pierrci

**Comment by mishig25** [comment]
@amitness thanks for notifying, working on it 👍
