### ISSUE TITLE
Error: Not found: /

### ISSUE THREAD

**Issue by bhavberi** [huggingface/doc-builder#456]
When building the hugging face hub using the command `doc-builder preview hub {path}/docs/hub/ --not_python_module` where path is my local path to the cloned repository, it is giving 404: Not Found Error.
I have followed the same steps as mentioned on the hugging face hub repository: https://github.com/huggingface/hub-docs#previewing-locally.

Can someone please help in what the issue could be and a possible solution for the same?

Terminal Logs: 
![image](https://github.com/huggingface/doc-builder/assets/43399374/4c5ab94c-11e2-42e9-90cd-cd0a08131029)

Website Output: 
![image](https://github.com/huggingface/doc-builder/assets/43399374/8744c507-b0a2-4d9b-90d7-4b900c5ee743)

**Comment by tomaarsen** [comment]
I encounter the same with `main` - I have to use an older commit to get it to work well.

**Comment by bhavberi** [comment]
Thanks for the help. Going around a month back in commits helped me get it working.

**Comment by sv-v5** [comment]
@bhavberi what commit did you revert back to?

I'm still having trouble with `doc-builder preview hub /hub-docs/docs/hub --not_python_module` for example and 

same error `Not Found: /`

im on debian bullseye, python3.10, node 20

**Comment by tomaarsen** [comment]
I went back to 3de0a0e9f824fc50e78c873732ef4a4ebaeb005b, though that's probably further than necessary.
