### ISSUE TITLE
Increase contrast of `<select>` in dark mode

### ISSUE THREAD

**Issue by severo** [huggingface/doc-builder#495]
<img width="637" alt="Capture d’écran 2024-04-12 à 09 47 33" src="https://github.com/huggingface/doc-builder/assets/1676121/1352f911-0484-4643-8f2c-5cb313f990ad">

Reported here by @not-lain: https://discord.com/channels/879548962464493619/897391062975385640/1228101829414486188

**Comment by not-lain** [comment]
@severo it seems they have fixed it for most places except for when managing my organization on huggingface
![image](https://github.com/huggingface/doc-builder/assets/70411813/22ab920b-cd09-45da-a046-ca179d0754d9)

**Comment by not-lain** [comment]
In love with the new UI, kudos to the dream team
![image](https://github.com/huggingface/doc-builder/assets/70411813/750fdbd8-76f9-4583-a98c-aaad00911d7d)

**Comment by not-lain** [comment]
great work everyone, and wishing you a wonderful day ❤️
