### ISSUE TITLE
Search dropdown gets overshadowed by the side overlay on Huggingface Docs

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/doc-builder#52]
Hello!

The search dropdown on [Huggingface docs](https://huggingface.co/docs/transformers/index) gets hidden behind the side overlay whenever anything is typed in it.

## Steps to reproduce
* Go to [https://huggingface.co/docs/transformers/index](https://huggingface.co/docs/transformers/index)
* Search anything, ex: BERT
* The search results would appear below the side overlay

## Screenshot
![unknown](https://user-images.githubusercontent.com/18682411/145732446-228aedcc-279a-4472-9586-e6a11cb55ee2.png)

Thank you & please do let me know in case you need any further information!

**Comment by julien-c** [comment]
for @mishig25 cc @gary149!

**Comment by mishig25** [comment]
@Vaibhavs10 thanks a lot for notifying! the fix will be live soon 😊
