### ISSUE TITLE
Documentation seems to hide part of the doc

### ISSUE THREAD

**Issue by Narsil** [huggingface/doc-builder#59]
In the live doc:https://huggingface.co/docs/transformers/master/en/model_doc/albert#transformers.AlbertTokenizer.sp_model_kwargs

When you expand/hover over the signature, it seems some arguments are not shown:

For instance this one: https://github.com/huggingface/transformers/blob/master/src/transformers/models/albert/tokenization_albert.py#L105

Is this a bug ?

**Comment by mishig25** [comment]
closing it since this issue is solved 👍
