### ISSUE TITLE
Add "open in hf spaces" gradio button

### ISSUE THREAD

**Issue by mishig25** [huggingface/doc-builder#73]
See proposed deign from @AK391 
<img width="500" alt="Screen Shot 2021-12-29 at 2 44 42 PM" src="https://user-images.githubusercontent.com/11827707/148359944-73e9580c-3508-4c78-b895-5e5b98749764.png">

As long as the design looks good with @sgugger & @gary149 , this task can be completed easily

**Comment by gary149** [comment]
Maybe we can try to horizontally align the badges to win vertical space?

**Comment by mishig25** [comment]
yeah that sounds good to me

**Comment by mishig25** [comment]
https://github.com/AK391/transformers/blob/master/docs/source/model_summary.mdx

**Comment by sgugger** [comment]
Works for me!

**Comment by AK391** [comment]
@mishig25 thanks, all spaces + badges added other than RAG, please review

**Comment by mishig25** [comment]
@AK391, could you create a PR https://github.com/huggingface/transformers?

**Comment by AK391** [comment]
@mishig25 thanks, PR here https://github.com/huggingface/transformers/pull/15106
