### ISSUE TITLE
Searching for specific arguments in classes / functions

### ISSUE THREAD

**Issue by mishig25** [huggingface/doc-builder#78]
Current: 
<img src="https://user-images.githubusercontent.com/11827707/151138569-a749f317-94e7-420d-b46d-fea64046cef3.png" width="500">

Previous (better results):
<img src="https://user-images.githubusercontent.com/11827707/151138578-1edc8c8a-01a8-47a4-bc12-1689487600ae.png" width="500">
<img src="https://user-images.githubusercontent.com/11827707/151138579-dbcc8b09-7e8c-426e-8d1e-fc0e347ff879.png" width="500">

**Comment by lewtun** [comment]
Not sure if this helps, but perhaps using [phrase search](https://docs.meilisearch.com/reference/features/search_parameters.html#query-q) will improve the precision:

> You can combine phrase search and normal queries in a single search request. In this case, MeiliSearch will first fetch all documents with exact matches to the given phrase(s), and then proceed with its default behavior.
