### ISSUE TITLE
Add "viewer" for html docs

### ISSUE THREAD

**Issue by coyotte508** [huggingface/doc-builder#97]
HTML docs are generated, and we can already view a non-interactive version by opening the HTML file.

It's possible to:

- add the css by copying the css on huggingface.co
- add interactivity by serving the html files from a webserver (from the correct folder)

Maybe we could also add a navbar with the list of html files (based on `_toctree.yml`) and have a command like `docbuilder --serve` ? It would open the docs on localhost.

It could be done through sveltekit: by running `npm run dev` , and going to http://localhost:3000/docs/transformers/master/en

**Comment by sgugger** [comment]
It would mostly be useful for team members than external contributors to be perfectly transparent (as contributors very rarely focus on the doc). However few people in the OSS team know how to get moon-landing running, so anything that makes the serving easier is welcome. 

Interactivity is not necessarily needed however as one would always need to rebuild the MDX files after a change, so can thus re-build the whole thing.

**Comment by julien-c** [comment]
is it really useful? 

if this adds maintenance cost, we shouldn't do it IMO, given that a very fast online build is available in CI anyways – most people including team members are going to use the CI IMO.

**Comment by mishig25** [comment]
we have [previewing now](https://github.com/huggingface/doc-builder#previewing)
